export type IconProps = {
  className?: string
  width?: string | number
  height?: string | number
  fill?: string
}

export type IconPropsExtend = IconProps & {
  mode?: 'regular' | 'solid'
}

export { AcerLogoIcon } from './AcerLogoIcon'
export { AngleDownIcon } from './AngleDownIcon'
export { AngleLeftIcon } from './AngleLeftIcon'
export { AngleRightIcon } from './AngleRightIcon'
export { AngleUpIcon } from './AngleUpIcon'
export { AppleLogoIcon } from './AppleLogoIcon'
export { ArrowRightIcon } from './ArrowRightIcon'
export { AsusLogoIcon } from './AsusLogoIcon'
export { BatteryIcon } from './BatteryIcon'
export { BoltLightning } from './BoltLightning'
export { BookMarkIcon } from './BookMarkIcon'
export { BoxIcon } from './BoxIcon'
export { BellIcon } from './BellIcon'
export { CameraIcon } from './CameraIcon'
export { CartIcon } from './CartIcon'
export { CheckIcon } from './CheckIcon'
export { CircleInfoIcon } from './CircleInfoIcon'
export { CircleThreePlusIcon } from './CircleThreePlusIcon'
export { ClipboardIcon } from './ClipboardIcon'
export { CloseIcon } from './CloseIcon'
export { CodeCompareIcon } from './CodeCompareIcon'
export { CommentStarIcon } from './CommentStarIcon'
export { DellLogoIcon } from './DellLogoIcon'
export { FacebookIcon } from './FacebookIcon'
export { FilterIcon } from './FilterIcon'
export { GiftIcon } from './GiftIcon'
export { GigabyteLogoIcon } from './GigabyteLogoIcon'
export { HandWavingIcon } from './HandWavingIcon'
export { HardDriveIcon } from './HardDriveIcon'
export { HeadsetIcon } from './HeadsetIcon'
export { HPLogoIcon } from './HPLogoIcon'
export { InstagramIcon } from './InstagramIcon'
export { LaptopMonitorIcon } from './LaptopMonitorIcon'
export { LayerGroupIcon } from './LayerGroupIcon'
export { LenovoLogoIcon } from './LenovoLogoIcon'
export { LocationIcon } from './LocationIcon'
export { LogoutIcon } from './LogoutIcon'
export { MapIcon } from './MapIcon'
export { MemoryIcon } from './MemoryIcon'
export { MenuIcon } from './MenuIcon'
export { MicrochipIcon } from './MicrochipIcon'
export { MicrosoftLogoIcon } from './MicrosoftLogoIcon'
export { MSILogoIcon } from './MSILogoIcon'
export { NotebookIcon } from './NotebookIcon'
export { PhoneCallIcon } from './PhoneCallIcon'
export { PlusIcon } from './PlusIcon'
export { RazerLogoIcon } from './RazerLogoIcon'
export { RepeatIcon } from './RepeatIcon'
export { SearchIcon } from './SearchIcon'
export { SortIcon } from './SortIcon'
export { StarIcon } from './StarIcon'
export { ShieldCheck } from './ShieldCheck'
export { SDCardIcon } from './SDCardIcon'
export { TiktokIcon } from './TiktokIcon'
export { TruckIcon } from './TruckIcon'
export { UserIcon } from './UserIcon'
export { WalletIcon } from './WalletIcon'
export { YoutubeIcon } from './YoutubeIcon'
